In [42]:
import numpy as np

In [43]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [44]:
a = np.array([1,2,3,4])
b = np.array([.5,.1,2.1,.5])

### Numpy arrays work with slycing just like python does

In [45]:
a[0]

1

In [46]:
a[1:]

array([2, 3, 4])

In [47]:
b[0:2]

array([0.5, 0.1])

### to get multiple values we can call a list within the selection

In [48]:
a[[0,2,3]]

array([1, 3, 4])

Array types 

In [49]:
a

array([1, 2, 3, 4])

In [50]:
a.dtype

dtype('int32')

In [51]:
b.dtype

dtype('float64')

In [52]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [53]:
np.array([1,2,3], dtype=np.int8)

array([1, 2, 3], dtype=int8)

### Dimensions and shapes

In [54]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [55]:
A.shape

(3, 3)

In [56]:
A.ndim

2

In [57]:
A.size

9

In [58]:
B = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [59]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [60]:
B.shape

(2, 2, 3)

In [61]:
B.ndim

3

In [62]:
B.size

12

### Indexing and slicing matrixes

In [63]:
A[0]

array([1, 2, 3])

In [64]:
A[0][1]

2

In [65]:
A[0,1]

2

In [66]:
B[0]

array([[12, 11, 10],
       [ 9,  8,  7]])

In [67]:
B[0][1]

array([9, 8, 7])

In [68]:
B[0][1][2]

7

In [74]:
B[0,1,2]

7

In [69]:
A[0][[0,2]]

array([1, 3])

In [70]:
A[0,[0,2]]

array([1, 3])

In [71]:
A[1] = np.array([8,8,8])

In [72]:
A

array([[1, 2, 3],
       [8, 8, 8],
       [7, 8, 9]])

In [75]:
A[2] = 99

In [76]:
A

array([[ 1,  2,  3],
       [ 8,  8,  8],
       [99, 99, 99]])

### Summary statistics

In [77]:
a = np.array([1,2,3,4])

In [78]:
a.sum()

10

In [79]:
a.mean()

2.5

In [80]:
a.std()

1.118033988749895

In [81]:
a.var()

1.25

In [82]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [83]:
A.sum()

45

In [84]:
A.mean()

5.0

In [85]:
A.std()

2.581988897471611

In [86]:
A.sum(axis=0) #gives sum of columns

array([12, 15, 18])

In [87]:
A.sum(axis=1) # gives sum of rows

array([ 6, 15, 24])

### Broadcasting a vectorized operations

In [88]:
a = np.arange(4)

In [89]:
a

array([0, 1, 2, 3])

In [90]:
a + 10

array([10, 11, 12, 13])

In [91]:
a * 10

array([ 0, 10, 20, 30])

In [93]:
a += 100 # This does modify the original array

In [94]:
a

array([100, 101, 102, 103])

In [98]:
a = np.arange(4)

In [99]:
b = np.array([10,10,10,10])

In [100]:
b

array([10, 10, 10, 10])

In [101]:
a + b

array([10, 11, 12, 13])

In [102]:
a * b

array([ 0, 10, 20, 30])

### Boolean arrays

In [103]:
a = np.arange(4)

In [104]:
a

array([0, 1, 2, 3])

In [105]:
a[[0,-1]]

array([0, 3])

In [106]:
a[[True, False, False, True]]

array([0, 3])

In [107]:
a >= 2

array([False, False,  True,  True])

In [108]:
a[a >= 2]

array([2, 3])

In [109]:
a.mean()

1.5

In [110]:
a[a >= a.mean()]

array([2, 3])

In [111]:
a[~(a > a.mean())]

array([0, 1])

In [112]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [114]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [115]:
A = np.random.randint(100,size=(3,3))

In [116]:
A

array([[15, 13, 37],
       [80, 79, 65],
       [39,  8, 73]])

In [117]:
A > 30

array([[False, False,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [118]:
A[A > 30]

array([37, 80, 79, 65, 39, 73])

### Linear Algebra

In [120]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [121]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [122]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [123]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [124]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [125]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Size of objects in Memory

In [128]:
import sys

# An integer in python is > 24 bytes

sys.getsizeof(1)

28

In [130]:
# Longs are even larger

sys.getsizeof(100**10)

36

In [132]:
# Nympy size is much smaller
np.dtype(int).itemsize

4

In [133]:
np.dtype(np.int8).itemsize

1

In [134]:
np.dtype(float).itemsize

8

### Useful Numpy functions

> Random

In [135]:
np.random.random(size=2)

array([0.46793664, 0.77297418])

In [136]:
np.random.normal(size=2)

array([ 0.29664661, -1.17623713])

In [137]:
np.random.rand(2,4)

array([[0.3396523 , 0.02788874, 0.11582432, 0.65825354],
       [0.31124793, 0.26748288, 0.33259757, 0.81797089]])

> arange

In [138]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
np.arange(2,5)

array([2, 3, 4])

In [140]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

> reshape

In [141]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [142]:
np.arange(10).reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

> linspace

In [143]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [144]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [146]:
np.linspace(0,1,20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

> zeroes, ones, empty

In [147]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [148]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [150]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [152]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [156]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [155]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

> Identity and eye

In [157]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [158]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [159]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [160]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [161]:
np.eye(8,4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])